// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7g6447r5lvCs9rY5GscOr-35alykAdiM',
    appId: '1:795944570538:web:f16b0cafa5048edb5e8ad3',
    messagingSenderId: '795944570538',
    projectId: 'fitness-d52dd',
    authDomain: 'fitness-d52dd.firebaseapp.com',
    storageBucket: 'fitness-d52dd.appspot.com',
    measurementId: 'G-PCDKTR254C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzCb-K30w_7RYlRCmeU2-RLVT75Oniddc',
    appId: '1:795944570538:android:9259e0e34a1224495e8ad3',
    messagingSenderId: '795944570538',
    projectId: 'fitness-d52dd',
    storageBucket: 'fitness-d52dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-TsxSx0Yi06dbOqzkDrr5aOJ8mrnANTM',
    appId: '1:795944570538:ios:62c79363a365ead35e8ad3',
    messagingSenderId: '795944570538',
    projectId: 'fitness-d52dd',
    storageBucket: 'fitness-d52dd.appspot.com',
    iosBundleId: 'com.example.fitnessapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-TsxSx0Yi06dbOqzkDrr5aOJ8mrnANTM',
    appId: '1:795944570538:ios:d662c6e96d8168375e8ad3',
    messagingSenderId: '795944570538',
    projectId: 'fitness-d52dd',
    storageBucket: 'fitness-d52dd.appspot.com',
    iosBundleId: 'com.example.fitnessapp.RunnerTests',
  );
}
